### PR TITLE
restructuring of the home and about us page

### PR DESCRIPTION
**Pull request by hebb00**
before 
aboutusBefore
after
aboutusAfter
before
homeBefore
after 
homeAfter

### CODE REVIEW

**Review by baokiddy — COMMENTED** [review]
I like the column formatting but really wondering if we could add some images or logo for visual interest. What do you think @hebb00 ?

**Comment by epowell101** [comment]
thanks for doing it!  

Great question re: visual interest - we may have a "Home of the Regen Rangers" theme soon that we could add, depending on success in getting some Lore like that designed of course

**Review by epowell101 — APPROVED** [review]
LGTM!

**Comment by hebb00** [comment]
thank you! @epowell101 
@baokiddy i agree with you 100% it would look way better with images, i can work on it as soon as the Regen Rangers theme is ready.

**Review by sarob — APPROVED** [review]
Great work! I am going to assume the images and regen rangers theme will be a future PR and merge this one.

**Comment by sarob** [comment]
Verified the merge and html creation worked. Looks great on mobile!Sean ***@***.*** On Mar 13, 2023, at 09:11, hebbs ***@***.***> wrote:﻿
thank you! @epowell101
@baokiddy i agree with you 100% it would look way better with images, i can work on it as soon as the Regen Rangers theme is ready.

**Comment by hebb00** [comment]
Yeah cool, I'd be happy to!
@sarob  thank you :)

**Pull request merged**
